  <!DOCTYPE html
PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <title>管理画面</title>
      <link rel="shortcut icon" href="<?php echo $this->img; ?>favicon.ico"/>
      <link type="text/css" rel="stylesheet" href="<?php echo $this->link; ?>"/>
    <script type="text/javascript" src="<?php echo $this->js; ?>jquery-1.3.2.min"></script>
    <script type="text/javascript" src="<?php echo $this->js; ?>masonry/jquery.masonry.js"></script>
    <script type="text/javascript">
     $(function(){
         $('.masonry_wrap').masonry();
     })
 </script>
    </head>
    <body>
        <div id="Wrapper">
            <div id="header">
                <div class="inner">                   
                </div>
            <div class="divider"></div>
            </div>
            <div id="central">                
                <div id="content"><div class="inner"><?php  echo $this->layout()->content ?></div></div>
                <div class="spacer"></div>
            </div>
            <div id="footer">
                <div class="divider divider_bottom"></div>
                <div class="inner"><?php   echo $this->layout()->footer ?></div>
            </div>
        </div>
    </body>
</html>