<ul>
    <li>
        <a href="index/page?category_type=schedule">schedule</a>
        <ul>
            <li><a href="index/page?category_type=schedule&edit_type=all_view">一覧</a></li>
            <li><a href="index/page?category_type=schedule&edit_type=create_page">新規ページ</a></li>
            <li><a href="index/page?category_type=schedule&edit_type=layout_master">レイアウトマスタ</a></li>
        </ul>
    </li>
    <li>
        <a href="index/page?category_type=message">message</a>
        <ul>
            <li><a href="index/page?category_type=message&edit_type=all_view">一覧</a></li>
            <li><a href="index/page?category_type=message&edit_type=create_page">新規ページ</a></li>
            <li><a href="index/page?category_type=message&edit_type=layout_master">レイアウトマスタ</a></li>
        </ul>
    </li>
    <li>
        <a href="index/page?category_type=paris">paris</a>
        <ul>
            <li><a href="index/page?category_type=paris&edit_type=all_view">一覧</a></li>
            <li><a href="index/page?category_type=paris&edit_type=create_page">新規ページ</a></li>
            <li><a href="index/page?category_type=paris&edit_type=layout_master">レイアウトマスタ</a></li>
        </ul>
    </li>
    <li>
        <a href="index/page?category_type=rojiura_cafe">rojiura_cafe</a>
        <ul>
            <li><a href="index/page?category_type=rojiura_cafe&edit_type=all_view">一覧</a></li>
            <li><a href="index/page?category_type=rojiura_cafe&edit_type=create_page">新規ページ</a></li>
            <li><a href="index/page?category_type=rojiura_cafe&edit_type=layout_master">レイアウトマスタ</a></li>
        </ul>
    </li>
    <li>
        <a href="index/page?category_type=rojiura_garden">rojiura_garden</a>
        <ul>
            <li><a href="index/page?category_type=rojiura_garden&edit_type=all_view">一覧</a></li>
            <li><a href="index/page?category_type=rojiura_garden&edit_type=create_page">新規ページ</a></li>
            <li><a href="index/page?category_type=rojiura_garden&edit_type=layout_master">レイアウトマスタ</a></li>
        </ul>
    </li>
    <li>
        <a href="index/page?category_type=gallery_youtube">youtube</a>
        <ul>
            <li><a href="index/page?category_type=gallery_youtube&edit_type=all_view">一覧</a></li>
            <li><a href="index/page?category_type=gallery_youtube&edit_type=create_page">新規ページ</a></li>
            <li><a href="index/page?category_type=gallery_youtube&edit_type=layout_master">レイアウトマスタ</a></li>
        </ul>
    </li>
    <li>
        <a href="index/page?category_type=gallery_photo">photo</a>
        <ul>
            <li><a href="index/page?category_type=gallery_photo&edit_type=all_view">一覧</a></li>
            <li><a href="index/page?category_type=gallery_photo&edit_type=create_page">新規ページ</a></li>
            <li><a href="index/page?category_type=gallery_photo&edit_type=layout_master">レイアウトマスタ</a></li>
        </ul>
    </li>
</ul>   
